/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Delvi
 */
public class CitasCoord extends javax.swing.JFrame {

    /**
     * Creates new form CitasCoord
     */
    public CitasCoord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo9 = new javax.swing.JPanel();
        PanelTabla = new javax.swing.JPanel();
        TextCitasRegistradas = new javax.swing.JLabel();
        TextCarrera = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFondo9.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout PanelTablaLayout = new javax.swing.GroupLayout(PanelTabla);
        PanelTabla.setLayout(PanelTablaLayout);
        PanelTablaLayout.setHorizontalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        PanelTablaLayout.setVerticalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        TextCitasRegistradas.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        TextCitasRegistradas.setForeground(new java.awt.Color(255, 255, 255));
        TextCitasRegistradas.setText("Citas registradas");

        TextCarrera.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        TextCarrera.setForeground(new java.awt.Color(255, 255, 255));
        TextCarrera.setText("Carrera :");

        javax.swing.GroupLayout PanelFondo9Layout = new javax.swing.GroupLayout(PanelFondo9);
        PanelFondo9.setLayout(PanelFondo9Layout);
        PanelFondo9Layout.setHorizontalGroup(
            PanelFondo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondo9Layout.createSequentialGroup()
                .addGroup(PanelFondo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFondo9Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(PanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFondo9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextCarrera))
                    .addGroup(PanelFondo9Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(TextCitasRegistradas)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        PanelFondo9Layout.setVerticalGroup(
            PanelFondo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondo9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(TextCarrera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextCitasRegistradas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CitasCoord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CitasCoord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CitasCoord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CitasCoord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CitasCoord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondo9;
    private javax.swing.JPanel PanelTabla;
    private javax.swing.JLabel TextCarrera;
    private javax.swing.JLabel TextCitasRegistradas;
    // End of variables declaration//GEN-END:variables
}

/*
 private javax.swing.JPanel PanelFondo9;  panel azul de fondo

    private javax.swing.JPanel PanelTabla; panel determinado para mostrar citas de coordinacion de carrera

    private javax.swing.JLabel TextCarrera; texto donde le indica al usuario-coordiandor su coordiancion de carrera


    private javax.swing.JLabel TextCitasRegistradas;  texto donde le indica al usuario-coordiandor sus citas registradas
*/