/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Delvi
 */
public class Coordinador extends javax.swing.JFrame {

    /**
     * Creates new form Coordinador
     */
    public Coordinador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo6 = new javax.swing.JPanel();
        Panel6Inicio = new javax.swing.JPanel();
        textNomEmpleado1 = new javax.swing.JLabel();
        NoEmpleado = new javax.swing.JTextField();
        TextContra = new javax.swing.JLabel();
        BotonLogin = new javax.swing.JButton();
        BotonRegistroCoord = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        NombreProyec4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFondo6.setBackground(new java.awt.Color(0, 0, 102));

        Panel6Inicio.setBackground(new java.awt.Color(204, 204, 204));

        textNomEmpleado1.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        textNomEmpleado1.setText("No. de empleado :");

        NoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoEmpleadoActionPerformed(evt);
            }
        });

        TextContra.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        TextContra.setText("Contraseña :");

        BotonLogin.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        BotonLogin.setText("Login");

        BotonRegistroCoord.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        BotonRegistroCoord.setText("¿No estas registrado?. Registrate aqui");

        Password.setText("jPasswordField1");

        javax.swing.GroupLayout Panel6InicioLayout = new javax.swing.GroupLayout(Panel6Inicio);
        Panel6Inicio.setLayout(Panel6InicioLayout);
        Panel6InicioLayout.setHorizontalGroup(
            Panel6InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel6InicioLayout.createSequentialGroup()
                .addGroup(Panel6InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel6InicioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel6InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textNomEmpleado1)
                            .addComponent(TextContra))
                        .addGap(18, 18, 18)
                        .addGroup(Panel6InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NoEmpleado)
                            .addComponent(Password, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                    .addGroup(Panel6InicioLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(BotonLogin))
                    .addGroup(Panel6InicioLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(BotonRegistroCoord)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        Panel6InicioLayout.setVerticalGroup(
            Panel6InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel6InicioLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(Panel6InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNomEmpleado1)
                    .addComponent(NoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(Panel6InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextContra)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotonLogin)
                .addGap(18, 18, 18)
                .addComponent(BotonRegistroCoord)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        NombreProyec4.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        NombreProyec4.setForeground(new java.awt.Color(255, 255, 255));
        NombreProyec4.setText("cITEs");

        javax.swing.GroupLayout PanelFondo6Layout = new javax.swing.GroupLayout(PanelFondo6);
        PanelFondo6.setLayout(PanelFondo6Layout);
        PanelFondo6Layout.setHorizontalGroup(
            PanelFondo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondo6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Panel6Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondo6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NombreProyec4)
                .addGap(181, 181, 181))
        );
        PanelFondo6Layout.setVerticalGroup(
            PanelFondo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondo6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(NombreProyec4)
                .addGap(18, 18, 18)
                .addComponent(Panel6Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coordinador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonLogin;
    private javax.swing.JButton BotonRegistroCoord;
    private javax.swing.JTextField NoEmpleado;
    private javax.swing.JLabel NombreProyec4;
    private javax.swing.JPanel Panel6Inicio;
    private javax.swing.JPanel PanelFondo6;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel TextContra;
    private javax.swing.JLabel textNomEmpleado1;
    // End of variables declaration//GEN-END:variables
}

/*
  private javax.swing.JButton BotonLogin; : boton para entrar login

    private javax.swing.JButton BotonRegistroCoord; boton para registrar perfil coordinador

    private javax.swing.JTextField NoEmpleado; : Texto donde indica el No. de empleado

    private javax.swing.JLabel NombreProyec4; : cITEs

    private javax.swing.JPanel Panel6Inicio; : Panel secundario donde el usuario hara interaccion de registro

    private javax.swing.JPanel PanelFondo6; : panel de fondo azul

    private javax.swing.JPasswordField Password; : : ingresar contraseña

    private javax.swing.JLabel TextContra; :   Texto donde indica la contraseña del usuario (coordinador)

    private javax.swing.JLabel textNomEmpleado1; :  Texto donde indica El nombre de empleado a ingresar (coordinador)
*/