/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


/**
 *
 * @author Delvi
 */
public class FrInicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public FrInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo1 = new javax.swing.JPanel();
        NombreProyec1 = new javax.swing.JLabel();
        lblite = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnCoord = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        lblCoord = new javax.swing.JLabel();
        lblslogan = new javax.swing.JLabel();
        subfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(5, 5));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFondo1.setBackground(new java.awt.Color(0, 39, 68));
        PanelFondo1.setMinimumSize(new java.awt.Dimension(1024, 768));
        PanelFondo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreProyec1.setBackground(new java.awt.Color(255, 255, 255));
        NombreProyec1.setFont(new java.awt.Font("Eras Bold ITC", 0, 56)); // NOI18N
        NombreProyec1.setForeground(new java.awt.Color(255, 255, 255));
        NombreProyec1.setText("cITEs");
        PanelFondo1.add(NombreProyec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 550, 60));

        lblite.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        lblite.setForeground(new java.awt.Color(255, 255, 255));
        lblite.setText("Instituto Tecnologico de Ensenada");
        PanelFondo1.add(lblite, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 680, -1, 30));

        lblUsuario.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("USUARIO");
        PanelFondo1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, 30));

        btnCoord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/imgCoord.png"))); // NOI18N
        btnCoord.setContentAreaFilled(false);
        btnCoord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoordActionPerformed(evt);
            }
        });
        PanelFondo1.add(btnCoord, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, -1, -1));

        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/imgUsuario.png"))); // NOI18N
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        PanelFondo1.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 150, 120));

        lblCoord.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        lblCoord.setForeground(new java.awt.Color(255, 255, 255));
        lblCoord.setText("COORDINADOR");
        PanelFondo1.add(lblCoord, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, 30));

        lblslogan.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        lblslogan.setForeground(new java.awt.Color(255, 255, 255));
        lblslogan.setText("!Agenda tu cita y evita las esperas!");
        PanelFondo1.add(lblslogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, 30));

        subfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/azulFondo.jpg"))); // NOI18N
        PanelFondo1.add(subfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, -200, 1710, 1190));

        getContentPane().add(PanelFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        FrAlumno Alumno = new FrAlumno();
        
        //Mostramos la interfaz del menu principal
        Alumno.setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnCoordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCoordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NombreProyec1;
    private javax.swing.JPanel PanelFondo1;
    private javax.swing.JButton btnCoord;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel lblCoord;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblite;
    private javax.swing.JLabel lblslogan;
    private javax.swing.JLabel subfondo;
    // End of variables declaration//GEN-END:variables
}

//private javax.swing.JToggleButton BotonAlumnoInicio;: Boton para ingresar al inicio de alumno y/o se registre/cree cuenta
   // private javax.swing.JButton BotonCoordInicio; : boton para ingresar al inicio Coordinador y/o cree cuenta
    //private javax.swing.JLabel InsertarIconoAlum;:Icono de alumno
   // private javax.swing.JLabel NombreProyecto;: cITEs
    //private javax.swing.JPanel Panel1Inicio;  Panel azul de fondo
    //private javax.swing.JPanel Panel2Inicio;  Panel gris donde estarn los botones e iconos
    //private javax.swing.JLabel insertarIconoCoord;  : Icono de coordinador