/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Delvi
 */
public class InicioAlum extends javax.swing.JFrame {

    /**
     * Creates new form InicioAlum
     */
    public InicioAlum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo4 = new javax.swing.JPanel();
        Panel3Inicio = new javax.swing.JPanel();
        textBienvenida = new javax.swing.JLabel();
        TextSelectCarrera = new javax.swing.JLabel();
        ComboBoxCarrera = new javax.swing.JComboBox<>();
        textHorarioDispo = new javax.swing.JLabel();
        ComboBoxHorario = new javax.swing.JComboBox<>();
        TextMotivos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextMotivoUsuario = new javax.swing.JTextArea();
        BotonVerCitaAlum = new javax.swing.JButton();
        BotonPedirCita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFondo4.setBackground(new java.awt.Color(0, 0, 102));

        Panel3Inicio.setBackground(new java.awt.Color(204, 204, 204));

        textBienvenida.setBackground(new java.awt.Color(255, 255, 255));
        textBienvenida.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        textBienvenida.setText("Bienvenido :");

        TextSelectCarrera.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        TextSelectCarrera.setText("Seleccione la coordinacion de su carrera : ");

        ComboBoxCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCarreraActionPerformed(evt);
            }
        });

        textHorarioDispo.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        textHorarioDispo.setText("Horarios disponibles: ");

        ComboBoxHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TextMotivos.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        TextMotivos.setText("Motivos de la cita :");

        TextMotivoUsuario.setColumns(20);
        TextMotivoUsuario.setRows(5);
        jScrollPane1.setViewportView(TextMotivoUsuario);

        BotonVerCitaAlum.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        BotonVerCitaAlum.setText("Ver mis citas");

        BotonPedirCita.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        BotonPedirCita.setText("Pedir cita");
        BotonPedirCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPedirCitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel3InicioLayout = new javax.swing.GroupLayout(Panel3Inicio);
        Panel3Inicio.setLayout(Panel3InicioLayout);
        Panel3InicioLayout.setHorizontalGroup(
            Panel3InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3InicioLayout.createSequentialGroup()
                .addGroup(Panel3InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel3InicioLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(TextMotivos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel3InicioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel3InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textBienvenida)
                            .addGroup(Panel3InicioLayout.createSequentialGroup()
                                .addComponent(TextSelectCarrera)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel3InicioLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(textHorarioDispo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboBoxHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Panel3InicioLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(BotonVerCitaAlum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonPedirCita)
                .addGap(30, 30, 30))
        );
        Panel3InicioLayout.setVerticalGroup(
            Panel3InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3InicioLayout.createSequentialGroup()
                .addComponent(textBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel3InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextSelectCarrera)
                    .addComponent(ComboBoxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel3InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textHorarioDispo)
                    .addComponent(ComboBoxHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(Panel3InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextMotivos)
                    .addGroup(Panel3InicioLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(Panel3InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonVerCitaAlum)
                    .addComponent(BotonPedirCita))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout PanelFondo4Layout = new javax.swing.GroupLayout(PanelFondo4);
        PanelFondo4.setLayout(PanelFondo4Layout);
        PanelFondo4Layout.setHorizontalGroup(
            PanelFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondo4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Panel3Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        PanelFondo4Layout.setVerticalGroup(
            PanelFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondo4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(Panel3Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelFondo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxCarreraActionPerformed

    private void BotonPedirCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPedirCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPedirCitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioAlum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonPedirCita;
    private javax.swing.JButton BotonVerCitaAlum;
    private javax.swing.JComboBox<String> ComboBoxCarrera;
    private javax.swing.JComboBox<String> ComboBoxHorario;
    private javax.swing.JPanel Panel3Inicio;
    private javax.swing.JPanel PanelFondo4;
    private javax.swing.JTextArea TextMotivoUsuario;
    private javax.swing.JLabel TextMotivos;
    private javax.swing.JLabel TextSelectCarrera;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel textBienvenida;
    private javax.swing.JLabel textHorarioDispo;
    // End of variables declaration//GEN-END:variables
}

/*
 private javax.swing.JButton BotonPedirCita; Boton para pedir cita solicitada

    private javax.swing.JButton BotonVerCitaAlum;  Boton para ver cita (en este caso registrada por alumno)

    private javax.swing.JComboBox<String> ComboBoxCarrera; Combo seleccionar la coordinacion de carrera que desee tener cita con el alumno)

    private javax.swing.JComboBox<String> ComboBoxHorario;  Combo seleccionar el horario dee cita de la coordinacion de carrera elegida

    private javax.swing.JPanel Panel2Inicio; panel gris emn el cual usuario-alumno interactua 

    private javax.swing.JPanel PanelFondo2; panel azul  de fondo

    private javax.swing.JTextArea TextMotivoUsuario;  Texto indicando motivos a ingresar

    private javax.swing.JLabel TextMotivos; area/espacio donde el usuario-alumno va escribir los motivos de la cita


    private javax.swing.JLabel TextSelectCarrera;  Texto indicando donde le usuario-alumno puede usar el ComboBoxCarrera

    private javax.swing.JScrollPane jScrollPane1;  OJO se esta considerando solo poner un combo box con motivos determinados y tener una opcion "otro" para abrir un espacio 
de texto adicional en acso especifico.

    private javax.swing.JLabel textBienvenida;: Texto expresando una bienvenida al usuario-alumno.

    private javax.swing.JLabel textHorarioDispo; Texto indicando donde le usuario-alumno pueda seleccioanr su horario de cita.
*/