/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Delvi
 */
public class InicioCoord extends javax.swing.JFrame {

    /**
     * Creates new form InicioCoord
     */
    public InicioCoord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel8Fondo = new javax.swing.JPanel();
        Panel8Inicio = new javax.swing.JPanel();
        IconoVerCitas = new javax.swing.JLabel();
        IconoCitaPend = new javax.swing.JLabel();
        BotonVerCitas = new javax.swing.JButton();
        BotonVerCitaPend = new javax.swing.JButton();
        TextBienvenidaCoord = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel8Fondo.setBackground(new java.awt.Color(0, 0, 102));

        Panel8Inicio.setBackground(new java.awt.Color(204, 204, 204));

        IconoVerCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VerCita.png.png"))); // NOI18N

        IconoCitaPend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CitaPendiente.png.png"))); // NOI18N

        BotonVerCitas.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        BotonVerCitas.setText("Ver citas");
        BotonVerCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerCitasActionPerformed(evt);
            }
        });

        BotonVerCitaPend.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        BotonVerCitaPend.setText("Ver citas pendientes");

        javax.swing.GroupLayout Panel8InicioLayout = new javax.swing.GroupLayout(Panel8Inicio);
        Panel8Inicio.setLayout(Panel8InicioLayout);
        Panel8InicioLayout.setHorizontalGroup(
            Panel8InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel8InicioLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(Panel8InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel8InicioLayout.createSequentialGroup()
                        .addComponent(IconoVerCitas)
                        .addGap(131, 131, 131)
                        .addComponent(IconoCitaPend)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Panel8InicioLayout.createSequentialGroup()
                        .addComponent(BotonVerCitas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(BotonVerCitaPend)
                        .addGap(23, 23, 23))))
        );
        Panel8InicioLayout.setVerticalGroup(
            Panel8InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel8InicioLayout.createSequentialGroup()
                .addGroup(Panel8InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel8InicioLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(IconoVerCitas))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel8InicioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IconoCitaPend)))
                .addGap(18, 18, 18)
                .addGroup(Panel8InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonVerCitas)
                    .addComponent(BotonVerCitaPend))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        TextBienvenidaCoord.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        TextBienvenidaCoord.setForeground(new java.awt.Color(255, 255, 255));
        TextBienvenidaCoord.setText("Bienvenido coordinador");

        javax.swing.GroupLayout Panel8FondoLayout = new javax.swing.GroupLayout(Panel8Fondo);
        Panel8Fondo.setLayout(Panel8FondoLayout);
        Panel8FondoLayout.setHorizontalGroup(
            Panel8FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel8FondoLayout.createSequentialGroup()
                .addGroup(Panel8FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel8FondoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(TextBienvenidaCoord))
                    .addGroup(Panel8FondoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Panel8Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        Panel8FondoLayout.setVerticalGroup(
            Panel8FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel8FondoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(TextBienvenidaCoord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel8Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel8Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel8Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVerCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerCitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonVerCitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioCoord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioCoord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioCoord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioCoord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioCoord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonVerCitaPend;
    private javax.swing.JButton BotonVerCitas;
    private javax.swing.JLabel IconoCitaPend;
    private javax.swing.JLabel IconoVerCitas;
    private javax.swing.JPanel Panel8Fondo;
    private javax.swing.JPanel Panel8Inicio;
    private javax.swing.JLabel TextBienvenidaCoord;
    // End of variables declaration//GEN-END:variables
}
/*
private javax.swing.JButton BotonVerCitaPend; : Boton donde le usuario-coordinador indicara que quiere ver sus Citas pendientes

    private javax.swing.JButton BotonVerCitas; :  Boton donde le usuario-coordinador indicara que quiere ver sus Citas 

    private javax.swing.JLabel IconoCitaPend; Icono de citas pendientes

    private javax.swing.JLabel IconoVerCitas; Icono de Ver citas

    private javax.swing.JPanel Panel8Fondo; panel azul de fondo

    private javax.swing.JPanel Panel8Inicio; panel gris donde el usuario-coordinador interactua 

    private javax.swing.JLabel TextBienvenidaCoord;  Texto que indica bienvenida al usuario-coordinador
*/