/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Delvi
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo1 = new javax.swing.JPanel();
        NombreProyec1 = new javax.swing.JLabel();
        Panel1nicio = new javax.swing.JPanel();
        InsertarIconoAlum = new javax.swing.JLabel();
        insertarIconoCoord = new javax.swing.JLabel();
        BotonAlumnoInicio = new javax.swing.JToggleButton();
        BotonCoordInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFondo1.setBackground(new java.awt.Color(0, 0, 102));

        NombreProyec1.setBackground(new java.awt.Color(255, 255, 255));
        NombreProyec1.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        NombreProyec1.setForeground(new java.awt.Color(255, 255, 255));
        NombreProyec1.setText("cITEs");

        Panel1nicio.setBackground(new java.awt.Color(204, 204, 204));

        InsertarIconoAlum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estud.png.png"))); // NOI18N

        insertarIconoCoord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coord.png.png"))); // NOI18N

        BotonAlumnoInicio.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        BotonAlumnoInicio.setText("ALUMNO");

        BotonCoordInicio.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        BotonCoordInicio.setText("COORDINADOR");

        javax.swing.GroupLayout Panel1nicioLayout = new javax.swing.GroupLayout(Panel1nicio);
        Panel1nicio.setLayout(Panel1nicioLayout);
        Panel1nicioLayout.setHorizontalGroup(
            Panel1nicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1nicioLayout.createSequentialGroup()
                .addGroup(Panel1nicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel1nicioLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(InsertarIconoAlum)
                        .addGap(149, 149, 149)
                        .addComponent(insertarIconoCoord))
                    .addGroup(Panel1nicioLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(BotonAlumnoInicio)
                        .addGap(84, 84, 84)
                        .addComponent(BotonCoordInicio)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        Panel1nicioLayout.setVerticalGroup(
            Panel1nicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1nicioLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(Panel1nicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InsertarIconoAlum)
                    .addComponent(insertarIconoCoord))
                .addGap(12, 12, 12)
                .addGroup(Panel1nicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonAlumnoInicio)
                    .addGroup(Panel1nicioLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(BotonCoordInicio)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelFondo1Layout = new javax.swing.GroupLayout(PanelFondo1);
        PanelFondo1.setLayout(PanelFondo1Layout);
        PanelFondo1Layout.setHorizontalGroup(
            PanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondo1Layout.createSequentialGroup()
                .addGroup(PanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFondo1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(NombreProyec1))
                    .addGroup(PanelFondo1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(Panel1nicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        PanelFondo1Layout.setVerticalGroup(
            PanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondo1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(NombreProyec1)
                .addGap(18, 18, 18)
                .addComponent(Panel1nicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelFondo1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonAlumnoInicio;
    private javax.swing.JButton BotonCoordInicio;
    private javax.swing.JLabel InsertarIconoAlum;
    private javax.swing.JLabel NombreProyec1;
    private javax.swing.JPanel Panel1nicio;
    private javax.swing.JPanel PanelFondo1;
    private javax.swing.JLabel insertarIconoCoord;
    // End of variables declaration//GEN-END:variables
}

//private javax.swing.JToggleButton BotonAlumnoInicio;: Boton para ingresar al inicio de alumno y/o se registre/cree cuenta
   // private javax.swing.JButton BotonCoordInicio; : boton para ingresar al inicio Coordinador y/o cree cuenta
    //private javax.swing.JLabel InsertarIconoAlum;:Icono de alumno
   // private javax.swing.JLabel NombreProyecto;: cITEs
    //private javax.swing.JPanel Panel1Inicio;  Panel azul de fondo
    //private javax.swing.JPanel Panel2Inicio;  Panel gris donde estarn los botones e iconos
    //private javax.swing.JLabel insertarIconoCoord;  : Icono de coordinador