/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Delvi
 */
public class PerfilUsuario extends javax.swing.JFrame {

    /**
     * Creates new form PerfilUsuario
     */
    public PerfilUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel10fondo = new javax.swing.JPanel();
        Panel9Inicio = new javax.swing.JPanel();
        IconoUsuario = new javax.swing.JLabel();
        TextCuenta = new javax.swing.JLabel();
        TextNombre = new javax.swing.JLabel();
        TextCorreo = new javax.swing.JLabel();
        TextContrase = new javax.swing.JLabel();
        BotonEliminarCuenta = new javax.swing.JButton();
        BotonEditNombre = new javax.swing.JButton();
        BotonEditCorreo = new javax.swing.JButton();
        BotonEditContrase = new javax.swing.JButton();
        NombreProyec6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel10fondo.setBackground(new java.awt.Color(0, 0, 102));

        IconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png.png"))); // NOI18N

        TextCuenta.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        TextCuenta.setText("Mi cuenta");

        TextNombre.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        TextNombre.setText("Nombre :");

        TextCorreo.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        TextCorreo.setText("Correo :");

        TextContrase.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        TextContrase.setText("Contraseña :");

        BotonEliminarCuenta.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        BotonEliminarCuenta.setText("Eliminar cuenta");

        BotonEditNombre.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        BotonEditNombre.setText("Editar");

        BotonEditCorreo.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        BotonEditCorreo.setText("Editar");

        BotonEditContrase.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        BotonEditContrase.setText("Editar");

        javax.swing.GroupLayout Panel9InicioLayout = new javax.swing.GroupLayout(Panel9Inicio);
        Panel9Inicio.setLayout(Panel9InicioLayout);
        Panel9InicioLayout.setHorizontalGroup(
            Panel9InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel9InicioLayout.createSequentialGroup()
                .addGroup(Panel9InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel9InicioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IconoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextCuenta))
                    .addGroup(Panel9InicioLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(Panel9InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel9InicioLayout.createSequentialGroup()
                                .addComponent(TextContrase)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                                .addComponent(BotonEditContrase))
                            .addGroup(Panel9InicioLayout.createSequentialGroup()
                                .addComponent(TextNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonEditNombre))
                            .addGroup(Panel9InicioLayout.createSequentialGroup()
                                .addComponent(TextCorreo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonEditCorreo)))))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel9InicioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonEliminarCuenta)
                .addGap(18, 18, 18))
        );
        Panel9InicioLayout.setVerticalGroup(
            Panel9InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel9InicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel9InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextCuenta)
                    .addComponent(IconoUsuario))
                .addGroup(Panel9InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel9InicioLayout.createSequentialGroup()
                        .addGroup(Panel9InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel9InicioLayout.createSequentialGroup()
                                .addGroup(Panel9InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextNombre)
                                    .addComponent(BotonEditNombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(TextCorreo))
                            .addGroup(Panel9InicioLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BotonEditCorreo)))
                        .addGap(32, 32, 32)
                        .addComponent(TextContrase))
                    .addGroup(Panel9InicioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotonEditContrase)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonEliminarCuenta)
                .addGap(10, 10, 10))
        );

        NombreProyec6.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        NombreProyec6.setForeground(new java.awt.Color(255, 255, 255));
        NombreProyec6.setText("cITEs");

        javax.swing.GroupLayout Panel10fondoLayout = new javax.swing.GroupLayout(Panel10fondo);
        Panel10fondo.setLayout(Panel10fondoLayout);
        Panel10fondoLayout.setHorizontalGroup(
            Panel10fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel10fondoLayout.createSequentialGroup()
                .addGroup(Panel10fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel10fondoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Panel9Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel10fondoLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(NombreProyec6)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        Panel10fondoLayout.setVerticalGroup(
            Panel10fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel10fondoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(NombreProyec6)
                .addGap(27, 27, 27)
                .addComponent(Panel9Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel10fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel10fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEditContrase;
    private javax.swing.JButton BotonEditCorreo;
    private javax.swing.JButton BotonEditNombre;
    private javax.swing.JButton BotonEliminarCuenta;
    private javax.swing.JLabel IconoUsuario;
    private javax.swing.JLabel NombreProyec6;
    private javax.swing.JPanel Panel10fondo;
    private javax.swing.JPanel Panel9Inicio;
    private javax.swing.JLabel TextContrase;
    private javax.swing.JLabel TextCorreo;
    private javax.swing.JLabel TextCuenta;
    private javax.swing.JLabel TextNombre;
    // End of variables declaration//GEN-END:variables
}

/*
  private javax.swing.JButton BotonEditContrase; Boton donde el usuario-coordinador indica que editara su contraseña


    private javax.swing.JButton BotonEditCorreo;  Boton donde el usuario-coordinador indica que editara su direccion de correo

    private javax.swing.JButton BotonEditNombre;  Boton donde el usuario-coordinador indica que editara su nombre

    private javax.swing.JButton BotonEliminarCuenta;  Boton donde el usuario-coordinador indica que desea eliminar su cuenta

    private javax.swing.JLabel IconoUsuario; Icono de perfil de usuario

    private javax.swing.JLabel NombreProyec6; cITEs

    private javax.swing.JPanel Panel10fondo; Panel azul de fondo

    private javax.swing.JPanel Panel9Inicio; Panel gris donde el usuario-coordinador  interactua 
 
    private javax.swing.JLabel TextContrase; Texto donde se le indica al  usuario-coordinador su contraseña

    private javax.swing.JLabel TextCorreo;  Texto donde se le indica al  usuario-coordinador su correo de carrera

    private javax.swing.JLabel TextCuenta;  Texto donde se le indica al  usuario-coordinador su cuenta

    private javax.swing.JLabel TextNombre;  Texto donde se le indica al  usuario-coordinador su nombre 
*/