/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Delvi
 */
public class RegistrarAlum extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarAlum
     */
    public RegistrarAlum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        PanelFondo3 = new javax.swing.JPanel();
        Panel3Inicio = new javax.swing.JPanel();
        TextNombre = new javax.swing.JLabel();
        IngresarNombreAlum = new javax.swing.JTextField();
        TextNoControlAlum = new javax.swing.JLabel();
        IngresarNoControl = new javax.swing.JTextField();
        TextCorreoinstALum = new javax.swing.JLabel();
        IngresarCorreoInstAlum = new javax.swing.JTextField();
        textContrase = new javax.swing.JLabel();
        BotonRegisAlum = new javax.swing.JButton();
        IngresarContraAlum = new javax.swing.JPasswordField();
        NombreProyec3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFondo3.setBackground(new java.awt.Color(0, 0, 102));

        Panel3Inicio.setBackground(new java.awt.Color(204, 204, 204));

        TextNombre.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        TextNombre.setText("Nombre : ");

        TextNoControlAlum.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        TextNoControlAlum.setText("No. de control :");

        TextCorreoinstALum.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        TextCorreoinstALum.setText("Correo institucional :");

        textContrase.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        textContrase.setText("Contraseña :");

        BotonRegisAlum.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        BotonRegisAlum.setText("Registrarme");

        IngresarContraAlum.setText("jPasswordField1");

        javax.swing.GroupLayout Panel3InicioLayout = new javax.swing.GroupLayout(Panel3Inicio);
        Panel3Inicio.setLayout(Panel3InicioLayout);
        Panel3InicioLayout.setHorizontalGroup(
            Panel3InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3InicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel3InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextCorreoinstALum)
                    .addGroup(Panel3InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TextNombre)
                        .addComponent(TextNoControlAlum))
                    .addGroup(Panel3InicioLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(textContrase)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel3InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IngresarNombreAlum)
                    .addComponent(IngresarNoControl)
                    .addComponent(IngresarCorreoInstAlum)
                    .addComponent(IngresarContraAlum, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addGap(54, 54, 54))
            .addGroup(Panel3InicioLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(BotonRegisAlum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel3InicioLayout.setVerticalGroup(
            Panel3InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3InicioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(Panel3InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextNombre)
                    .addComponent(IngresarNombreAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel3InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextNoControlAlum)
                    .addComponent(IngresarNoControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel3InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCorreoinstALum)
                    .addComponent(IngresarCorreoInstAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel3InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textContrase)
                    .addComponent(IngresarContraAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotonRegisAlum)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        NombreProyec3.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        NombreProyec3.setForeground(new java.awt.Color(255, 255, 255));
        NombreProyec3.setText("cITEs");

        javax.swing.GroupLayout PanelFondo3Layout = new javax.swing.GroupLayout(PanelFondo3);
        PanelFondo3.setLayout(PanelFondo3Layout);
        PanelFondo3Layout.setHorizontalGroup(
            PanelFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondo3Layout.createSequentialGroup()
                .addGroup(PanelFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFondo3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Panel3Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFondo3Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(NombreProyec3)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        PanelFondo3Layout.setVerticalGroup(
            PanelFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondo3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(NombreProyec3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel3Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarAlum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegisAlum;
    private javax.swing.JPasswordField IngresarContraAlum;
    private javax.swing.JTextField IngresarCorreoInstAlum;
    private javax.swing.JTextField IngresarNoControl;
    private javax.swing.JTextField IngresarNombreAlum;
    private javax.swing.JLabel NombreProyec3;
    private javax.swing.JPanel Panel3Inicio;
    private javax.swing.JPanel PanelFondo3;
    private javax.swing.JLabel TextCorreoinstALum;
    private javax.swing.JLabel TextNoControlAlum;
    private javax.swing.JLabel TextNombre;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel textContrase;
    // End of variables declaration//GEN-END:variables
}

/*
private javax.swing.JButton BotonRegisAlum; Boton de registro alumno

    private javax.swing.JPasswordField IngresarContraAlum; Espacio donde el usuario-alumno ingresa la contraseña

    private javax.swing.JTextField IngresarCorreoInstAlum;  Espacio donde ingresa el usuario-alumno correo

    private javax.swing.JTextField IngresarNoControl;   Espacio donde ingresa el usuario-alumno el numero de control

    private javax.swing.JTextField IngresarNombreAlum;    Espacio donde ingresa el usuario-alumno su nombre

    private javax.swing.JLabel NombreProyec3; : cITEs

    private javax.swing.JPanel Panel3Inicio; :  Panel gris donde interactua el usuario-alumno 

    private javax.swing.JPanel PanelFondo3;panel azul de fondo

    private javax.swing.JLabel TextCorreoinstALum; Texto donde indica  en donde ingresara su correo institucional

    private javax.swing.JLabel TextNoControlAlum; Texto donde indica  en donde ingresara su no. control

    private javax.swing.JLabel TextNombre; Texto donde indica  en donde ingresara su nombre

    private javax.swing.JScrollBar jScrollBar1; 

    private javax.swing.JLabel textContrase; Texto donde indica  en donde ingresara su contraseña
*/