/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Delvi
 */
public class RegistroCoord extends javax.swing.JFrame {

    /**
     * Creates new form RegistroCoord
     */
    public RegistroCoord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo7 = new javax.swing.JPanel();
        Panel7Inicio = new javax.swing.JPanel();
        TextNombre = new javax.swing.JLabel();
        IngresarNombreCoord = new javax.swing.JTextField();
        TextNoEmplead = new javax.swing.JLabel();
        IngresarNoEmpleado = new javax.swing.JTextField();
        TextCorreoCarre = new javax.swing.JLabel();
        IngresarCorreoCarrer = new javax.swing.JTextField();
        TextContrase = new javax.swing.JLabel();
        BotonRegisCoord = new javax.swing.JButton();
        PasswordCoord = new javax.swing.JPasswordField();
        NombreProyec5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFondo7.setBackground(new java.awt.Color(0, 0, 102));

        Panel7Inicio.setBackground(new java.awt.Color(204, 204, 204));

        TextNombre.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        TextNombre.setText("Nombre :");

        IngresarNombreCoord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarNombreCoordActionPerformed(evt);
            }
        });

        TextNoEmplead.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        TextNoEmplead.setText("No. de empleado :");

        IngresarNoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarNoEmpleadoActionPerformed(evt);
            }
        });

        TextCorreoCarre.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        TextCorreoCarre.setText("Correo de carrera:");

        TextContrase.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        TextContrase.setText("Contraseña :");

        BotonRegisCoord.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        BotonRegisCoord.setText("Registrarme");

        PasswordCoord.setText("jPasswordField1");

        javax.swing.GroupLayout Panel7InicioLayout = new javax.swing.GroupLayout(Panel7Inicio);
        Panel7Inicio.setLayout(Panel7InicioLayout);
        Panel7InicioLayout.setHorizontalGroup(
            Panel7InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel7InicioLayout.createSequentialGroup()
                .addGroup(Panel7InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel7InicioLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(BotonRegisCoord))
                    .addGroup(Panel7InicioLayout.createSequentialGroup()
                        .addGroup(Panel7InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel7InicioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TextNoEmplead))
                            .addGroup(Panel7InicioLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(TextNombre)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel7InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IngresarNombreCoord, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngresarNoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel7InicioLayout.createSequentialGroup()
                        .addGroup(Panel7InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel7InicioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TextCorreoCarre))
                            .addGroup(Panel7InicioLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(TextContrase)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel7InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IngresarCorreoCarrer)
                            .addComponent(PasswordCoord, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        Panel7InicioLayout.setVerticalGroup(
            Panel7InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel7InicioLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(Panel7InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextNombre)
                    .addComponent(IngresarNombreCoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel7InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextNoEmplead)
                    .addComponent(IngresarNoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel7InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextCorreoCarre)
                    .addComponent(IngresarCorreoCarrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel7InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextContrase)
                    .addComponent(PasswordCoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotonRegisCoord)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        NombreProyec5.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        NombreProyec5.setForeground(new java.awt.Color(255, 255, 255));
        NombreProyec5.setText("cITEs");

        javax.swing.GroupLayout PanelFondo7Layout = new javax.swing.GroupLayout(PanelFondo7);
        PanelFondo7.setLayout(PanelFondo7Layout);
        PanelFondo7Layout.setHorizontalGroup(
            PanelFondo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondo7Layout.createSequentialGroup()
                .addGroup(PanelFondo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFondo7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Panel7Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFondo7Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(NombreProyec5)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        PanelFondo7Layout.setVerticalGroup(
            PanelFondo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondo7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(NombreProyec5)
                .addGap(18, 18, 18)
                .addComponent(Panel7Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelFondo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarNombreCoordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarNombreCoordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarNombreCoordActionPerformed

    private void IngresarNoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarNoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarNoEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCoord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCoord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCoord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCoord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCoord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegisCoord;
    private javax.swing.JTextField IngresarCorreoCarrer;
    private javax.swing.JTextField IngresarNoEmpleado;
    private javax.swing.JTextField IngresarNombreCoord;
    private javax.swing.JLabel NombreProyec5;
    private javax.swing.JPanel Panel7Inicio;
    private javax.swing.JPanel PanelFondo7;
    private javax.swing.JPasswordField PasswordCoord;
    private javax.swing.JLabel TextContrase;
    private javax.swing.JLabel TextCorreoCarre;
    private javax.swing.JLabel TextNoEmplead;
    private javax.swing.JLabel TextNombre;
    // End of variables declaration//GEN-END:variables
}

/*
private javax.swing.JButton BotonRegisCoord; Boton donde el usuario-Coordinador indica su registro terminado

    private javax.swing.JTextField IngresarCorreoCarrer;: Espacio donde el  usuario-Coordinador ingresa su correo de carrera

    private javax.swing.JTextField IngresarNoEmpleado;   Espacio donde el  usuario-Coordinador ingresa su  no. empleado

    private javax.swing.JTextField IngresarNombreCoord; Espacio donde el  usuario-Coordinador ingresa su nombre

    private javax.swing.JLabel NombreProyec5; cITEs

    private javax.swing.JPanel Panel7Inicio; Panel gris donde el  usuario-Coordinador interactua

    private javax.swing.JPanel PanelFondo7; Panel azul de fondo 

    private javax.swing.JPasswordField PasswordCoord;  Espacio donde el  usuario-Coordinador ingresa su contraseña

    private javax.swing.JLabel TextContrase;   Texto donde se le indical al  usuario-Coordinador ingresa su contraseña

    private javax.swing.JLabel TextCorreoCarre;    Texto donde se le indical al  usuario-Coordinador ingresa su correo de carrera/coordinacion

    private javax.swing.JLabel TextNoEmplead;usuario-Coordinador  Texto donde se le indical al  usuario-Coordinador ingresar su no. empleado

    private javax.swing.JLabel TextNombre;usuario-Coordinador Texto donde se le indical al  usuario-Coordinador ingresa su nombre
*/